from typing import Optional, Literal, List
from pydantic import BaseModel, Field


class Defendant(BaseModel):
    defendant_name: Optional[str] = Field(default=None, description="被告姓名")
    has_defense_attorney: Optional[bool] = Field(default=None, description="被告是否有選任辯護人")
    defense_attorney_name: Optional[str] = Field(default=None, description="辯護人名稱（若 has_defense_attorney 為 true 時填寫，否則填空字串）")
    indictment_changed: Optional[bool] = Field(default=None, description="是否變更起訴法條（若同一條文但項次不同，仍視為變更）")
    original_indictment_articles: Optional[List[str]] = Field(default=None, description="原本起訴法條（若 indictment_changed 為 true 時填寫，有幾條填幾條）")
    changed_indictment_articles: Optional[List[str]] = Field(default=None, description="變更起訴法條（若 indictment_changed 為 true 時填寫，有幾條填幾條）")
    has_new_old_law_issue: Optional[bool] = Field(default=None, description="本件是否有新舊法適用的問題")
    new_old_law_disputed_article: Optional[str] = Field(default=None, description="新舊法爭議的法條（若 has_new_old_law_issue 為 true 時填寫）")
    has_contradictory_statements: Optional[bool] = Field(default=None, description="是否有審理中與偵查中就核心事實或主要辯解內容出現矛盾、否認、或重大變更之陳述")
    confession_status: Optional[Literal["完全認罪", "完全否認", "部分"]] = Field(default=None, description="是否在本次審理中認罪")
    is_full_acquittal: Optional[bool] = Field(default=None, description="本件是否為全部無罪判決")
    is_acquittal_due_to_insufficient_evidence: Optional[bool] = Field(default=None, description="是否因為罪證不足而獲得全部無罪判決（若 is_full_acquittal 為 true 時填寫）")
    is_other_verdict: Optional[bool] = Field(default=None, description="本件是否為無罪、有罪以外的判決結果")
    is_conviction: Optional[bool] = Field(default=None, description="本件是否為有罪判決")
    crime_list: Optional[List[str]] = Field(default=None, description="本次罪名清單（若 is_conviction 為 true 時填寫，例如：「三人以上共同詐欺取財罪」、「洗錢未遂罪」，關鍵字是 XXX 罪）")
    violated_law_articles: Optional[List[str]] = Field(default=None, description="所違反的法律條文（若 is_conviction 為 true 時填寫，列出具體法條與條次，關鍵字 XXX 條 XXX 項）")
    is_fixed_term_imprisonment: Optional[bool] = Field(default=None, description="本件是否為有期徒刑")
    fixed_term_years: Optional[int] = Field(default=None, description="有期徒刑年數（若 is_fixed_term_imprisonment 為 true 時填寫，否則填 0）")
    fixed_term_months: Optional[int] = Field(default=None, description="有期徒刑月數（若 is_fixed_term_imprisonment 為 true 時填寫，否則填 0）")
    is_life_imprisonment: Optional[bool] = Field(default=None, description="本件是否為無期徒刑")
    is_death_penalty: Optional[bool] = Field(default=None, description="本件是否為死刑")
    is_detention: Optional[bool] = Field(default=None, description="本件是否為拘役")
    detention_days: Optional[int] = Field(default=None, description="拘役天數（若 is_detention 為 true 時填寫，否則填 0）")
    has_concurrent_fine: Optional[bool] = Field(default=None, description="本件是否併科罰金")
    fine_amount: Optional[int] = Field(default=None, description="罰金金額（新臺幣，若 has_concurrent_fine 為 true 時填寫，否則填 0）")
    may_convert_to_fine: Optional[bool] = Field(default=None, description="本件是否得易科罰金（易科罰金不需要折算率）")
    has_probation: Optional[bool] = Field(default=None, description="本件是否給予緩刑")
    probation_period: Optional[str] = Field(default=None, description="給予緩刑之期間（若 has_probation 為 true 時填寫，例如：「2年」、「3年6月」）")
    has_mitigation_articles: Optional[bool] = Field(default=None, description="本件是否有適用減刑的條文")
    mitigation_articles: Optional[str] = Field(default=None, description="適用減刑的條文為（若 has_mitigation_articles 為 true 時填寫）")
    has_settlement: Optional[bool] = Field(default=None, description="本件是否與被害人或告訴人和解")
    settlement_amount: Optional[int] = Field(default=None, description="和解之總金額（新臺幣，若 has_settlement 為 true 時填寫，否則填 0）")
    is_settlement_fulfilled: Optional[bool] = Field(default=None, description="法院是否認定和解已經履行（若 has_settlement 為 true 時填寫）")
    is_settlement_installment: Optional[bool] = Field(default=None, description="本件和解是否分期（若 has_settlement 為 true 時填寫）")
    has_witnesses: Optional[bool] = Field(default=None, description="本件是否有證人（被告以外之人，包含共同被告）")
    witness_testified_in_investigation: Optional[bool] = Field(default=None, description="證人是否有在偵查中作證（若 has_witnesses 為 true 時填寫）")
    witness_testified_in_trial: Optional[bool] = Field(default=None, description="證人是否有在審判中作證（若 has_witnesses 為 true 時填寫）")
    has_seized_items: Optional[bool] = Field(default=None, description="本件是否有遭扣押物品")
    seized_items: Optional[List[str]] = Field(default=None, description="本件遭扣押物品（若 has_seized_items 為 true 時填寫）")
    has_confiscated_items: Optional[bool] = Field(default=None, description="本件是否遭沒收物品")
    confiscated_items: Optional[List[str]] = Field(default=None, description="本件遭沒收物品（若 has_confiscated_items 為 true 時填寫）")
    is_continuous_offense: Optional[Literal["是", "否", "未提及"]] = Field(default=None, description="本件被告是否屬於接續犯")
    is_first_instance: Optional[bool] = Field(default=None, description="是否為一審判決")
    is_second_instance: Optional[bool] = Field(default=None, description="是否為二審判決")
    is_third_instance: Optional[bool] = Field(default=None, description="是否為三審判決")
    has_previous_instance: Optional[bool] = Field(default=None, description="是否有原審（前審）判決（是否為上訴案件）")
    is_reversed_and_remanded: Optional[bool] = Field(default=None, description="是否撤銷改判（若 has_previous_instance 為 true 時填寫）")
    is_sentence_reduced: Optional[bool] = Field(default=None, description="是否減輕量刑（若 is_reversed_and_remanded 為 true 時填寫）")
    is_sentence_increased: Optional[bool] = Field(default=None, description="是否加重量刑（若 is_reversed_and_remanded 為 true 時填寫）")
    is_law_article_changed_from_previous: Optional[bool] = Field(default=None, description="是否變更原審（前審）適用法條（若 has_previous_instance 為 true 時填寫）")
    changed_law_articles: Optional[List[str]] = Field(default=None, description="變更法條為（若 is_law_article_changed_from_previous 為 true 時填寫，有幾條填幾條）")
    previous_instance_confession_status: Optional[Literal["完全認罪", "完全否認", "部分", "不適用"]] = Field(default=None, description="原審（前審）是否有認罪（若 has_previous_instance 為 true 時填寫）")
    current_instance_confession_status: Optional[Literal["完全認罪", "完全否認", "部分", "不適用"]] = Field(default=None, description="本件（上訴案件）是否有認罪（若 has_previous_instance 為 true 時填寫）")
    has_inconsistent_statements_with_previous: Optional[bool] = Field(default=None, description="是否有與原審答辯或主要陳述內容不一致之情形（若 has_previous_instance 為 true 時填寫）")
    statement_difference_description: Optional[str] = Field(default=None, description="若有，請以一句話描述前後陳述的主要差異（若 has_inconsistent_statements_with_previous 為 true 時填寫）")


class CaseMetadata(BaseModel):
    first_instance: Optional[bool] = Field(default=None, description="是否為地方法院判決")
    second_instance: Optional[bool] = Field(default=None, description="是否為高等法院判決")
    third_instance: Optional[bool] = Field(default=None, description="是否為最高法院判決")
    case_type: Optional[Literal["刑法", "民法", "行政法"]] = Field(default=None, description="案件類型，只能為：刑法，民法，行政法其中一種")
    jtitle_type: Optional[Literal[
        "詐欺", "毒品", "竊盜", "侵占", "妨害性自主", "傷害", "公共危險",
        "槍砲彈藥刀械", "偽造文書", "其他刑事", "債務給付類", "侵權行為／損害賠償類",
        "婚姻家庭類", "物權類", "公司／商事類", "勞資爭議類", "保險類", "其他民事"
    ]] = Field(default=None, description="案件標題類型")


class Filter(BaseModel):
    jid: Optional[str] = Field(default=None, description="判決書ID（例：TPHM,113,上訴,6418,20250617,1）")
    jid_full: Optional[str] = Field(default=None, description="完整判決書名稱，（例：臺灣高等法院刑事判決113年度上訴字第6418號）必填")
    jyear: Optional[int] = Field(default=None, description="年度（例：113）")
    jcase: Optional[str] = Field(default=None, description="案件類型（例：上訴）")
    jno: Optional[str] = Field(default=None, description="案件編號（例：6418）")
    jdate: Optional[int] = Field(default=None, description="判決日期（例：20250617）")
    defendants: Optional[List[Defendant]] = Field(default=None, description="逐一被告之結構化資訊清單（可省略）")
    case_metadata: Optional[CaseMetadata] = Field(default=None, description="案件元資料與審級/類型等資訊（可省略）")
    defendants_role: Optional[str] = Field(default=None, description="被告角色定位與功能，說明被告在整體犯罪結構中的位置與職能。若問句與此項無關直接留空。")
    A_fact: Optional[str] = Field(default=None, description="法院確認的行為事實與過程，純描述，不含法律用語。敘述法院確認的客觀行為內容與過程，包含行為時間、地點、方式、參與人等要素。若問句與此項無關直接留空。")
    B_claim: Optional[str] = Field(default=None, description="被告主張與抗辯理由，無論採信與否均完整列出。列出被告於偵查或審理階段的抗辯內容與理由，無論法院是否採信都必須完整保留。若有多次不同說法可取主要版本或最終陳述。不得混入法院評論。若問句與此項無關直接留空。")
    C_court_finding: Optional[str] = Field(default=None, description="法院認定哪些事實成立，採信哪些證據或供述。敘述法院最終認為哪些事實成立、採信哪些證據、排除哪些辯詞。可含「法院認為」「法院採信」「法院不採信」等語。若問句與此項無關直接留空。")
    D_court_reason: Optional[str] = Field(default=None, description="法院推論、採信理由、法條適用與量刑考量。敘述法院的推論過程、採信邏輯、法律適用與量刑考量。可包含法律詞彙、判斷語氣與條文引用。若問句與此項無關直接留空。")
    E_legal_eval: Optional[str] = Field(default=None, description="法院最終法律評價、罪名與競合處理結果。簡述法院最終的法律結論，包括罪名、競合與量刑方向。可使用法律用語（如「共同正犯」「想像競合」「從一重詐欺罪處斷」等）。若問句與此項無關直接留空。")
    negated_fields: Optional[List[str]] = Field(default=None, description="需要否定的欄位列表。當使用者問句中包含否定語義（如：沒有、不是、未、非等），將對應的欄位名稱加入此列表。欄位名稱應使用完整路徑，如：'defendants.has_defense_attorney'、'case_metadata.first_instance'、'defendants.confession_status' 等。")
    # case_fact_summary: Optional[str] = Field(default=None, description="無法律評價。提供整體可閱讀的案件輪廓，描述被害人、主要行為流程、整體案件脈絡。若問句與此項無關直接留空。")

